
DROP TABLE IF EXISTS `mkyong`.`PIZZA` ;
CREATE TABLE `mkyong`.`PIZZA` (
    `PIZZA_ID` BIGINT(20) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    `NOM` VARCHAR(45) NOT NULL,
    `PRIX` FLOAT NOT NULL,
    PRIMARY KEY (`PIZZA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `mkyong`.`ingredient` ;
CREATE TABLE `mkyong`.`ingredient` (
    `INGREDIENT_ID` BIGINT(20) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    `NOM` VARCHAR(45) NOT NULL,
    `PRIX` FLOAT NOT NULL,
    `PIZZA_REF` BIGINT(20) UNSIGNED DEFAULT NULL,
    PRIMARY KEY (`INGREDIENT_ID`),
    KEY `FKPIZZA` (`PIZZA_REF`),
    CONSTRAINT `FKPIZZA` FOREIGN KEY (`PIZZA_REF`) REFERENCES `PIZZA` (`PIZZA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS `mkyong`.`client`;
CREATE TABLE `mkyong`.`client` (
    `CLIENT_ID` BIGINT(20) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    `NOM` VARCHAR(45) NOT NULL,
    `PRENOM` VARCHAR(45) NOT NULL,
    `TELEPHONE` varchar(10) DEFAULT NULL,
    `ADRESSE` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`CLIENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
   
/*  Table de conversion des types MySQL vers les classes Java
http://dev.mysql.com/doc/refman/5.0/en/connector-j-reference-type-conversions.html */

      




