/* Creation de votre utilisateur au préalable */

create database ITALIA;
grant all on ITALIA.* to cdsappl@'localhost';
SET PASSWORD FOR cdsappl@'localhost' = PASSWORD('iConsult2000');

/* Définition de la table PIZZA */

DROP TABLE IF EXISTS `ITALIA`.`PIZZA` ;
CREATE TABLE `ITALIA`.`PIZZA` (
    `PIZZA_ID` BIGINT(20) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    `NOM` VARCHAR(45) NOT NULL,
    `PRIX` FLOAT NOT NULL,
    PRIMARY KEY (`PIZZA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*
 * Définition de la table ingrédient
 */
DROP TABLE IF EXISTS `ITALIA`.`ingredient` ;
CREATE TABLE `ITALIA`.`ingredient` (
    `INGREDIENT_ID` BIGINT(20) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    `NOM` VARCHAR(45) NOT NULL,
    `PRIX` FLOAT NOT NULL,
    PRIMARY KEY (`INGREDIENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*
 * Définition de la table jointure ingredient_pizza
 */
DROP TABLE IF EXISTS `ITALIA`.`ingredient_pizza` ;
CREATE TABLE `ITALIA`.`ingredient_pizza` (
    `INGPIZZA_ID` BIGINT(20) UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    `NOM_INGREDIENT` VARCHAR(45) DEFAULT NULL,
    `NOM_PIZZA` VARCHAR(45) DEFAULT NULL,
    `INGREDIENT_REF` BIGINT(20) UNSIGNED DEFAULT NULL,
    `PIZZA_REF` BIGINT(20) UNSIGNED DEFAULT NULL,
    PRIMARY KEY (`INGPIZZA_ID`),
    KEY `FKPIZZA` (`PIZZA_REF`),
    KEY `FKINGREDIENT` (`INGREDIENT_REF`),
    CONSTRAINT `FKPIZZA` FOREIGN KEY (`PIZZA_REF`) REFERENCES `PIZZA` (`PIZZA_ID`),
    CONSTRAINT `FKINGREDIENT` FOREIGN KEY (`INGREDIENT_REF`) REFERENCES `ingredient` (`INGREDIENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*
 * Définition de la table customer
 */
DROP TABLE IF EXISTS `ITALIA`.`customer`;
CREATE TABLE  `ITALIA`.`customer` (
  `CUSTOMER_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NOT NULL,
  `PRENOM` VARCHAR(45) DEFAULT NULL,
  `ADRESSE` VARCHAR(255) NOT NULL,
  `TELEPHONE` VARCHAR(10) DEFAULT NULL,
  `CREATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/* Jeu de données
 * Steeve + Lory + Manuel
 *  */



/*  Table de conversion des types MySQL vers les classes Java
http://dev.mysql.com/doc/refman/5.0/en/connector-j-reference-type-conversions.html */

      




